spring.cloud.stream.kafka.binder.brokers: localhost:9094

spring.cloud.stream:
  function:
    definition: externalMessageProducer
  bindings:
    externalMessageProducer-out-0:
      destination: external_messages
  kafka:
      bindings:
        externalMessageProducer-out-0:
          producer:
            configuration:
              value:
                serializer: org.springframework.kafka.support.serializer.JsonSerializer